/*
 * Copyright (C) 2015-2020 Socionext Inc.
 */
#include "miscvbotx.h"
#include "system_ctrl.h"
#include "hv_error.h"
#include "hv_sleep.h"
#include "reg_access.h"
#include "videoif_regs.h"
//------------------------------------------------------------------------------
#ifndef NULL
#define NULL												0
#endif // NULL
//------------------------------------------------------------------------------
// error check & if (c) is a error, return (c)
#define CHECK_ERROR(c) {						\
	if ((c) != ERR_OK) {						\
		return (c);								\
	}											\
}
// register access setting
#define SET_ACCESS(a, p, c, n) {				\
	(a).p_port = (p);							\
	(a).p_com = (c);							\
	(a).count = (n);							\
}
// command setting
#define SET_COMMAND(c, i, a, d, m) {			\
	(c)[(i)].addr = (a);						\
	(c)[(i)].data = (d);						\
	(c)[(i)].mask = (m);						\
}
// resigter block access setting
#define SET_BLOCK_ACCESS(b, p, a, l, d) {		\
	(b).p_port = (p);							\
	(b).addr = (a);								\
	(b).length = (l);							\
	(b).p_data = (d);							\
}
// block data setting
#define SET_BLOCK_DATA(b, i, d) {				\
	(b)[(i)] = (d);								\
}
//------------------------------------------------------------------------------
extern uint32_t vbotx_set_video_format_wo_tx_link(vbotx_video *p_video);
//------------------------------------------------------------------------------
// vbotx_set_sg_format
//   sets the supported video format as signal generator for VBO Tx
//
//   Prototype:
//     uint32_t vbotx_set_sg_format(vbotx_sg_video *p_video)
//
//   Parameters:
//     p_video    Pointer to structure of vbotx_sg_video to hold video format property
//
//   Returns:
//     ERR_OK if successful, otherwise a system error code depending on the function.
//
//   Description:
//     This function sets the video format to use as a signal generator for VBO Tx.
//     Because the video signal for VBO Tx is output by using the video signal
//     generated by hdmitx_set_sg_format() function, it must be performed beforehand.
//     This function must be called after vbotx_init function is called.
//     The supported video format as signal generator is as follows.
//       system_video_format:
//         SYSTEM_VFORM_720x480P_5994or60_4v3
//         SYSTEM_VFORM_720x480P_5994or60_16v9
//         SYSTEM_VFORM_1280x720P_50_16v9
//         SYSTEM_VFORM_1280x720P_5994or60_16v9
//         SYSTEM_VFORM_1920x1080P_2398or24_16v9
//         SYSTEM_VFORM_1920x1080P_25_16v9
//         SYSTEM_VFORM_1920x1080P_2997or30_16v9
//         SYSTEM_VFORM_1920x1080P_50_16v9
//         SYSTEM_VFORM_1920x1080P_5994or60_16v9
//         SYSTEM_VFORM_3840x2160P_2398or24_16v9
//         SYSTEM_VFORM_3840x2160P_25_16v9
//         SYSTEM_VFORM_3840x2160P_2997or30_16v9
//         SYSTEM_VFORM_3840x2160P_50_16v9
//         SYSTEM_VFORM_3840x2160P_5994or60_16v9
//         SYSTEM_VFORM_4096x2160P_2398or24_256v135
//         SYSTEM_VFORM_4096x2160P_25_256v135
//         SYSTEM_VFORM_4096x2160P_2997or30_256v135
//         SYSTEM_VFORM_4096x2160P_50_256v135
//         SYSTEM_VFORM_4096x2160P_5994or60_256v135
//       system_deep_color:
//         SYSTEM_DEEP_COLOR_8BIT
//         SYSTEM_DEEP_COLOR_10BIT
//
//   Examples:
//     system_port port = {SYSTEM_PORT_NUMBER_0, 0, SYSTEM_PORT_TYPE_VBO,
//                         SYSTEM_RXTX_TYPE_TX, SYSTEM_CHIP_NUMBER_0};
//     vbotx_sg_video vform;
//     vform.port = port;
//     vform.video_format = SYSTEM_VFORM_3840x2160P_5994or60_16v9;
//     vform.deep_color = SYSTEM_DEEP_COLOR_10BIT;
//     vbotx_set_sg_format(&vform);
//------------------------------------------------------------------------------
uint32_t vbotx_set_sg_format(vbotx_sg_video *p_video)
{
	vbotx_video vf;
	uint32_t ret;

	if (p_video == NULL) {
		return ERR_NULL_POINTER;
	}

	vf.rx_port = vf.tx_port = p_video->port;
	vf.rx_port.port_type = SYSTEM_PORT_TYPE_LVDS;		// for vbotx_hvpol_setting()
	vf.rx_port.rxtx_type = SYSTEM_RXTX_TYPE_RX;
	vf.rx_video_format = vf.tx_video_format = p_video->video_format;
	vf.rx_deep_color = vf.tx_deep_color = p_video->deep_color;

	ret = vbotx_set_video_format_wo_tx_link(&vf);
	CHECK_ERROR(ret);

	return ret;
}
//------------------------------------------------------------------------------
