
eywa_src_list := $(wildcard $(LOCAL_PATH)/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/log/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/support/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/db/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/db/config/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/db/config/iniparser/*.c)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/db/config/iniprovider/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/common/db/securec/*.c)

eywa_src_list += $(wildcard $(LOCAL_PATH)/platform/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rtc/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rtc/rtc/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/follow/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/source/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiodetect/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/ops/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/kernelmsg/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/module/uart/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/module/sdk/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/touch/module/usb/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiocodec/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiocodec/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiocodec/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiocodec/module/ap8224/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiocodec/module/ap8232/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/module/ad82120/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/module/acm8625/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audioamplifier/module/tas5805m/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiotoi2s/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiotoi2s/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiotoi2s/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiotoi2s/module/es7210/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/audiotoi2s/module/es7243/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/ite66353/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/asw3642/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/gsv2715/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/gsv2705/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/gsv6712/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/lt8668sx/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/gsv2712/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/gsv2702/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/hdmiswitch/module/wxqLt8641UX_U5/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/dp2hdmi/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/dp2hdmi/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/dp2hdmi/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/dp2hdmi/module/ite6563/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/dp2hdmi/module/csv5363/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/module/gsv2202E/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/module/lt8711/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbc2hdmi/module/lt8711UXE1/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/vga2hdmi/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/vga2hdmi/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/vga2hdmi/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/vga2hdmi/module/ms9282/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/netswitch/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/netswitch/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/netswitch/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/netswitch/module/rtl8305/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/netswitch/module/rtl8367/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/jsa1141/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/v2000/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/risa311/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/tsl2572/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/tsl2561/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/ltrx140a/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/als199/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/lightsensor/module/stk3210/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/gsensor/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/gsensor/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/gsensor/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/gsensor/module/mc3416/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/airsensor/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/airsensor/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/airsensor/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/airsensor/module/am1008/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/airsensor/module/mcuam1008/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/nfc/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/nfc/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/nfc/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/nfc/module/mcunfc/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/rk_gd32f310g8/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/mt_gd32f310g8/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/gd32f330r8/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/gd32f305rb/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/mcu/module/at32f407rc/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/powersensor/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/powersensor/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/powersensor/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/sensor/powersensor/module/bl0942/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/mn869129/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/mn869129/*.c)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/nt68411/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/ite6265/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/lt8668sxc/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/ite6563/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/lt6711a/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/CS5803aq/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/avout/module/gsv6125/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/vgaedid/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/watchdog/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/liftbracket/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/liftbracket/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/liftbracket/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/liftbracket/module/XbhLiftCH341bracket/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rj45tousb/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rj45tousb/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rj45tousb/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rj45tousb/module/ax88179/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/rj45tousb/module/ax88279/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/pdic/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/pdic/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/pdic/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/pdic/module/rts5450m/*.cpp)

eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbhub/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbhub/interface/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbhub/module/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbhub/module/hl817/*.cpp)
eywa_src_list += $(wildcard $(LOCAL_PATH)/logic/usbhub/module/hl817/*.c)