/*
 * Copyright (C) 2015-2020 Socionext Inc.
 */
#include <stdio.h>
#include <stdint.h>
#include "hv_error.h"

// -----------------------------------------------------------------------------
uint32_t hv_errno = ERR_OK;			// number of last error
// -----------------------------------------------------------------------------
char *hv_strerr(uint32_t err)
{
	static char ret[11];

#ifdef __XC16
	sprintf(ret, "0x%08lX", err);
#else
	sprintf(ret, "0x%08X", err);
#endif
	return (
		  (err == ERR_OK)										? "OK"
		: (err == ERR_NG)										? "NG"
		: (err == ERR_INVALID_INDEX)							? "INVALID INDEX"
		: (err == ERR_INVALID_HANDLE)							? "INVALID HANDLE"
		: (err == ERR_INVALID_SIZE)								? "INVALID SIZE"
		: (err == ERR_INVALID_DATA)								? "INVALID DATA"
		: (err == ERR_TIMEOUT)									? "TIMEOUT"
		: (err == ERR_RETRY)									? "RETRY"
		: (err == ERR_NULL_POINTER)								? "NULL POINTER"
		: (err == ERR_TX_UPDATE_CONTROL_RETRY)					? "TX UPDATE CONTROL RETRY"

		: (err == ERR_HDMIRX_INIT)								? "HDMIRX INIT"
		: (err == ERR_HDMIRX_INVALID_PORT)						? "HDMIRX INVALID PORT"
		: (err == ERR_HDMIRX_VIDEO_FORMAT)						? "HDMIRX VIDEO FORMAT"
		: (err == ERR_HDMIRX_COLOR_FORMAT)						? "HDMIRX COLOR FORMAT"
		: (err == ERR_HDMIRX_DEEP_COLOR)						? "HDMIRX DEEP COLOR FORMAT"
		: (err == ERR_HDMIRX_AUDIO_FORMAT)						? "HDMIRX AUDIO FORMAT"
		: (err == ERR_HDMIRX_AUDIO_COMBINATION)					? "HDMIRX AUDIO SAMPLING FREQ COMBINATION"
		: (err == ERR_HDMIRX_VIDEO_FORMAT_DETECT_RETRY)			? "HDMIRX VIDEO FORMAT DETECT RETRY"
		: (err == ERR_HDMIRX_AVI_INFOFRAME_VERSION)				? "HDMIRX AVI INFOFRAME VERSION"
		: (err == ERR_HDMIRX_AUDIO_INFOFRAME_VERSION)			? "HDMIRX AUDIO INFOFRAME VERSION"
		: (err == ERR_HDMIRX_DEEP_COLOR_DETECT_RETRY)			? "HDMIRX DEEP COLOR DETECT RETRY"
		: (err == ERR_HDMIRX_TMDS_CALIBRATION_RETRY)			? "HDMIRX TMDS CALIBRATION RETRY"
		: (err == ERR_HDMIRX_ABORT)								? "HDMIRX ABORT"

		: (err == ERR_HDCPRX14_AKECMD_NORMAL_END)				? "HDCPRX14 AKECMD NORMAL END"
		: (err == ERR_HDCPRX14_AKECMD_NOT_FOUND)				? "HDCPRX14 AKECMD NOT FOUND"
		: (err == ERR_HDCPRX14_CHECKSUM_NOT_MATCH)				? "HDCPRX14 CHECKSUM NOT MATCH"
		: (err == ERR_HDCPRX14_BKSV_IRREGULAR)					? "HDCPRX14 BKSV IRREGULAR"
		: (err == ERR_HDCPRX14_MAX_DEVICE_COUNT_EXCEEDED)		? "HDCPRX14 MAX DEVICE_COUNT EXCEEDED"
		: (err == ERR_HDCPRX14_AKESTA_READ_RETRY)				? "HDCPRX14 AKESTA READ RETRY"
		: (err == ERR_HDCPRX22_AKECMD_NORMAL_END)				? "HDCPRX22 AKECMD NORMAL END"
		: (err == ERR_HDCPRX22_AKECMD_NOT_FOUND)				? "HDCPRX22 AKECMD NOT FOUND"
		: (err == ERR_HDCPRX22_AKESTA_READ_RETRY)				? "HDCPRX22 AKESTA READ RETRY"
		: (err == ERR_HDCPRX22_WRONG_DEVICE_KEY)				? "HDCPRX22 WRONG DEVICE KEY"
		: (err == ERR_HDCPRX22_AKE_SEND_H_PRIME_NOT_READ)		? "HDCPRX22 AKE_SEND_H_PRIME NOT READ"
		: (err == ERR_HDCPRX22_V_VD_NOT_MATCH)					? "HDCPRX22 V-V' NOT MATCH"
		: (err == ERR_HDCPRXXX_PACKET_HEADER_BCH_ERROR)			? "HDCPRXXX PACKET HEADER BCH ERROR"
		: (err == ERR_HDCPRXXX_PACKET_BODY_BCH_ERROR)			? "HDCPRXXX PACKET BODY BCH ERROR"
		: (err == ERR_HDCPRXXX_ABORT)							? "HDCPRXXX ABORT"

		: (err == ERR_VBORX_INIT)								? "VBORX INIT"
		: (err == ERR_VBORX_RECEIVE_FORMAT)						? "VBORX RECEIVE FORMAT"
		: (err == ERR_VBORX_BOOT_SEQ_RETRY)						? "VBORX BOOT SEQUENCE RETRY"
		: (err == ERR_VBORX_CDR_LOCK_DETECT_RETRY)				? "VBORX CDR LOCK DETECT RETRY"
		: (err == ERR_VBORX_LINK_UP_DETECT_RETRY)				? "VBORX LINK UP DETECT RETRY"
		: (err == ERR_VBORX_ABORT)								? "VBORX ABORT"

		: (err == ERR_HDMITX_INIT)								? "HDMITX INIT"
		: (err == ERR_HDMITX_VIDEO_FORMAT)						? "HDMITX VIDEO FORMAT"
		: (err == ERR_HDMITX_COLOR_FORMAT)						? "HDMITX COLOR FORMAT"
		: (err == ERR_HDMITX_DEEP_COLOR)						? "HDMITX DEEP COLOR FORMAT"
		: (err == ERR_HDMITX_VIDEO_DATA)						? "HDMITX VIDEO DATA"
		: (err == ERR_HDMITX_AUDIO_FORMAT)						? "HDMITX AUDIO FORMAT"
		: (err == ERR_HDMITX_AUDIO_COMBINATION)					? "HDMITX AUDIO FORMAT COMBINATION"
		: (err == ERR_HDMITX_480DS_DOWNCON_SEQ_RETRY)			? "HDMITX 480P DOWNCONVERT SEQUENCE RETRY"
		: (err == ERR_HDMITX_HPD_INACTIVE)						? "HDMITX HPD INACTIVE"
		: (err == ERR_HDMITX_RXSENSE_INACTIVE)					? "HDMITX RXSENSE INACTIVE"
		: (err == ERR_HDMITX_ABORT)								? "HDMITX ABORT"

		: (err == ERR_DDCTX_AKECMD_NORMAL_END)					? "DDCTX AKECMD NORMAL END"
		: (err == ERR_DDCTX_AKECMD_NOT_FOUND)					? "DDCTX AKECMD NOT FOUND"
		: (err == ERR_DDCTX_DDC_NO_ACK_REPLY)					? "DDCTX DDC NO ACK REPLY"
		: (err == ERR_DDCTX_AKESTA_READ_RETRY)					? "DDCTX AKESTA READ RETRY"
		: (err == ERR_DDCTX_DDC_ACCESS_RETRY)					? "DDCTX DDC ACCESS RETRY"
		: (err == ERR_DDCTX_DDC_FIXED_LOW_LEVEL)				? "DDCTX DDC FIXED LOW LEVEL"

		: (err == ERR_HDCPTX14_AKECMD_NORMAL_END)				? "HDCPTX14 AKECMD NORMAL END"
		: (err == ERR_HDCPTX14_AKECMD_NOT_FOUND)				? "HDCPTX14 AKECMD NOT FOUND"
		: (err == ERR_HDCPTX14_CHECKSUM_NOT_MATCH)				? "HDCPTX14 CHECKSUM NOT MATCH"
		: (err == ERR_HDCPTX14_AKSV_BKSV_IRREGULAR)				? "HDCPTX14 AKSV BKSV IRREGULAR"
		: (err == ERR_HDCPTX14_DDC_NO_ACK_REPLY)				? "HDCPTX14 DDC NO ACK REPLY"
		: (err == ERR_HDCPTX14_AKESTA_READ_RETRY)				? "HDCPTX14 AKESTA READ RETRY"
		: (err == ERR_HDCPTX14_DDC_ACCESS_RETRY)				? "HDCPTX14 DDC ACCESS RETRY"
		: (err == ERR_HDCPTX14_DDC_FIXED_LOW_LEVEL)				? "HDCPTX14 DDC FIXED LOW LEVEL"
		: (err == ERR_HDCPTX14_RI_NOT_MATCH)					? "HDCPTX14 RI NOT MATCH"
		: (err == ERR_HDCPTX14_VH_NOT_MATCH)					? "HDCPTX14 VH NOT MATCH"
		: (err == ERR_HDCPTX14_REPEATER_0_IN_READING_KSVLIST)	? "HDCPTX14 REPEATER 0 IN READING KSVLIST"
		: (err == ERR_HDCPTX14_TIMEOUT_IN_READING_KSVLIST)		? "HDCPTX14 TIMEOUT IN READING KSVLIST"
		: (err == ERR_HDCPTX14_KSV_OR_SHA1_COMMAND_ERROR)		? "HDCPTX14 KSV OR SHA1 COMMAND ERROR"
		: (err == ERR_HDCPTX14_MAX_CASCADE_EXCEEDED)			? "HDCPTX14 MAX_CASCADE_EXCEEDED"
		: (err == ERR_HDCPTX14_MAX_DEVS_EXCEEDED)				? "HDCPTX14 MAX_DEVS_EXCEEDED"
		: (err == ERR_HDCPTX14_MISSING_CTLX_SIGNAL_ERROR)		? "HDCPTX14 MISSING CTLX SIGNAL ERROR"
		: (err == ERR_HDCPTX14_EXTRA_CTLX_SIGNAL_ERROR)			? "HDCPTX14 EXTRA CTLX SIGNAL ERROR"
		: (err == ERR_HDCPTX14_INIT_AUTH_RETRY)					? "HDCPTX14 INIT AUTHENTICATION RETRY"
		: (err == ERR_HDCPTX22_AKECMD_NORMAL_END)				? "HDCPTX22 AKECMD NOMAL END"
		: (err == ERR_HDCPTX22_AKECMD_NOT_FOUND)				? "HDCPTX22 AKECMD NOT FOUND"
		: (err == ERR_HDCPTX22_DDC_NO_ACK_REPLY)				? "HDCPTX22 DDC NO ACK REPLY"
		: (err == ERR_HDCPTX22_AKESTA_READ_RETRY)				? "HDCPTX22 AKESTA READ RETRY"
		: (err == ERR_HDCPTX22_DDC_ACCESS_RETRY)				? "HDCPTX22 DDC ACCESS RETRY"
		: (err == ERR_HDCPTX22_RXSTATUS_READ_RETRY)				? "HDCPTX22 RXSTATUS READ RETRY"
		: (err == ERR_HDCPTX22_DDC_FIXED_LOW_LEVEL)				? "HDCPTX22 DDC FIXED LOW LEVEL"
		: (err == ERR_HDCPTX22_TIMEOUT_ERROR)					? "HDCPTX22 TIMEOUT ERROR"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_1)			? "HDCPTX22 SIGNATURE NOT MATCH 1"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_2)			? "HDCPTX22 SIGNATURE NOT MATCH 2"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_3)			? "HDCPTX22 SIGNATURE NOT MATCH 3"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_4)			? "HDCPTX22 SIGNATURE NOT MATCH 4"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_5)			? "HDCPTX22 SIGNATURE NOT MATCH 5"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_6)			? "HDCPTX22 SIGNATURE NOT MATCH 6"
		: (err == ERR_HDCPTX22_SIGNATURE_NOT_MATCH_7)			? "HDCPTX22 SIGNATURE NOT MATCH 7"
		: (err == ERR_HDCPTX22_MESSAGE_SIZE_ERROR)				? "HDCPTX22 MESSAGE SIZE ERROR"
		: (err == ERR_HDCPTX22_MESSAGE_ID_ERROR)				? "HDCPTX22 MESSAGE ID ERROR"
		: (err == ERR_HDCPTX22_H_HD_OR_L_LD_OR_M_MD_NOT_MATCH)	? "HDCPTX22 H-H', L-L' OR M-M' NOT MATCH"
		: (err == ERR_HDCPTX22_MAX_CASCADE_EXCEEDED)			? "HDCPTX22 MAX_CASCADE_EXCEEDED"
		: (err == ERR_HDCPTX22_MAX_DEVS_EXCEEDED)				? "HDCPTX22 MAX_DEVS_EXCEEDED"
		: (err == ERR_HDCPTX22_K_OVER_63)						? "HDCPTX22 K OVER 63"
		: (err == ERR_HDCPTX22_REAUTH_REQ)						? "HDCPTX22 REAUTH_REQ"
		: (err == ERR_HDCPTX22_INIT_AUTH_RETRY)					? "HDCPTX22 INIT AUTHENTICATION RETRY"
		: (err == ERR_HDCPTX22_RXSTATUS_READY)					? "HDCPTX22 RXSTATUS READY"
		: (err == ERR_HDCPTX22_SEQ_NUM_V_ROLL_OVER)				? "HDCPTX22 SEQ_NUM_V ROLL OVER"
		: (err == ERR_HDCPTX22_SEQ_NUM_V_INVALID)				? "HDCPTX22 SEQ_NUM_V INVALID"
		: (err == ERR_HDCPTX22_STREAM_MANAGE_RETRY)				? "HDCPTX22 STREAM MANAGEMENT RETRY"
		: (err == ERR_HDCPTX22_LC_INIT_RETRY)					? "HDCPTX22 LC_INIT RETRY"
		: (err == ERR_HDCPTXXX_ABORT)							? "HDCPTXXX ABORT"

		: (err == ERR_VBOTX_INIT)								? "VBOTX INIT"
		: (err == ERR_VBOTX_TRANSMIT_FORMAT)					? "VBOTX TRANSMIT FORMAT"
		: (err == ERR_VBOTX_HOT_PLUG_DETECT_RETRY)				? "VBOTX HOT PLUG DETECT RETRY"
		: (err == ERR_VBOTX_PLL_LOCK_DETECT_RETRY)				? "VBOTX PLL LOCK DETECT RETRY"
		: (err == ERR_VBOTX_LINK_UP_COMPLETE_RETRY)				? "VBOTX LINK UP COMPLETE RETRY"
		: (err == ERR_VBOTX_ABORT)								? "VBOTX ABORT"

		: (err == ERR_LVDSTX_INIT)								? "LVDSTX INIT"
		: (err == ERR_LVDSTX_TRANSMIT_FORMAT)					? "LVDSTX TRANSMIT FORMAT"
		: (err == ERR_LVDSTX_ABORT)								? "LVDSTX ABORT"
		: ret
	);
}
// -----------------------------------------------------------------------------
