/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _Included_INIFILE
#define _Included_INIFILE
#ifdef __cplusplus
extern "C" {
#endif
char *GetIniKeyString(const char *title,char *key,const char *filename);
int GetIniKeyInt(const char *title,const char *key,const char *filename);
#ifdef __cplusplus
}
#endif
#endif
